apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-nums
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-nums
    app.kubernetes.io/part-of: test-app-omyb
  name: nodejs-no-dockerfile-nums
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-nums
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-nums
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-wout-tenant/test-app-omyb/nodejs-no-dockerfile-nums@sha256:53a8cb97808252ef93e1e3cdf6194e04149f09023ef474a400b6ef64cf15753c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
